//
//  NewsListWorker.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 09.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListWorkerLogic: class {
    func fetchNews(completion: @escaping (_ courses: [News])->())
}

class NewsListWorker: NewsListWorkerLogic {
    
    func fetchNews(completion: @escaping (_ courses: [News])->()) {
            let urlString = "https://swiftbook.ru//wp-content/uploads/api/api_courses"
            guard let url = URL(string: urlString) else { return }
            
            URLSession.shared.dataTask(with: url) { (data, _, _) in
                guard let data = data else { return }
                
                do {
                    let decoder = JSONDecoder()
                    decoder.keyDecodingStrategy = .convertFromSnakeCase
                    let courses = try decoder.decode([News].self, from: data)
                    completion(courses)
                } catch let error {
                    print("Error serialization json", error)
                }
                
            }.resume()
        }
}
