//
//  NewsListInteractor.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 09.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListBusinessLogic {
    func fetchNews(request: NewsList.FetchNews.Request)
}

protocol NewsListDataStore {
    var news: [News] { get }
}

class NewsListInteractor: NewsListBusinessLogic, NewsListDataStore {
    
    var presenter: NewsListPresentationLogic?
    var worker: NewsListWorker?
    var news: [News] = []
    
    // MARK: Do something
    
    func fetchNews(request: NewsList.FetchNews.Request) {
        NetworkManager.shared.fetchData { news in
            self.news = news
            let response = NewsList.FetchNews.Response(news: news)
            self.presenter?.presentNews(response: response)
        }
    }
}
