//
//  NewsListWorker.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 09.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NewsListWorker {
    func getDisplayedNews(from news: [News]) -> [NewsList.FetchNews.ViewModel.DisplayedNews] {
        
        var displayedNews: [NewsList.FetchNews.ViewModel.DisplayedNews] = []
        
        news.forEach { news in
            let title = news.title
            let imageData = fetchImage(from: news.urlToImage)
            
            let displayedNew = NewsList.FetchNews.ViewModel.DisplayedNews(
                title: title,
                imageData: imageData
            )
            
            displayedNews.append(displayedNew)
        }
        
        return displayedNews
    }
    
    private func fetchImage(from imageURL: String?) -> Data? {
        ImageManager.shared.getImageData(from: imageURL)
    }
}
