//
//  NewsDetailsRouter.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 06.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsDetailsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NewsDetailsDataPassing {
    var dataStore: NewsDetailsDataStore? { get }
}

class NewsDetailsRouter: NSObject, NewsDetailsRoutingLogic, NewsDetailsDataPassing {
    
    weak var viewController: NewsDetailsViewController?
    var dataStore: NewsDetailsDataStore?
}
