//
//  NewsDetailsWorker.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 06.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NewsDetailsWorker {
    func fetchImage(from imageURL: String?) -> Data? {
        ImageManager.shared.getImageData(from: imageURL)
    }
}
