//
//  NewsDetailsViewController.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 06.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsDisplayLogic: class {
    func displayDetails(viewModel: NewsDetails.ShowDetails.ViewModel)
}

class NewsDetailsViewController: UIViewController {
    
    
    //@IBOutlet private var nameTextField: UITextField!
    
    var interactor: NewsDetailsBusinessLogic?
    var router: (NSObjectProtocol & NewsDetailsRoutingLogic & NewsDetailsDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        NewsDetailsConfigurator.shared.counfure(with: self)
        showDetails()
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Do something
    
    func showDetails() {
        let request = NewsDetails.ShowDetails.Request()
        interactor?.showDetails(request: request)
    }
}

extension NewsDetailsViewController: NewsDetailsDisplayLogic {
    
    func displayDetails(viewModel: NewsDetails.ShowDetails.ViewModel) {
//        courseNameLabel.text = viewModel.displayedDetails.courseName
//        numberOfLessonsLabel.text = viewModel.displayedDetails.numberOfLessons
//        numberOfTestsLabel.text = viewModel.displayedDetails.numberOfTests
//
//        guard let image = viewModel.displayedDetails.imageData else { return }
//        courseImage.image = UIImage(data: image)
//
//        let favouriteImage = viewModel.displayedDetails.isFavourite ? #imageLiteral(resourceName: "heartIcon") : #imageLiteral(resourceName: "unselectedHeart")
//        favouriteButton.setImage(favouriteImage, for: .normal)
    }
}
