//
//  NewsDetailsInteractor.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 06.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsBusinessLogic {
    func showDetails(request: NewsDetails.ShowDetails.Request)
}

protocol NewsDetailsDataStore {
    var news: News! { get set }
}

final class NewsDetailsInteractor: NewsDetailsBusinessLogic, NewsDetailsDataStore {
    
    var presenter: NewsDetailsPresentationLogic?
    var news: News!
    
    init(news: News) {
        self.news = news
    }
    
    // MARK: Do something
    
    func showDetails(request: NewsDetails.ShowDetails.Request) {
        let response = NewsDetails.ShowDetails.Response(news: news)
        presenter?.presentDetails(response: response)
    }
}
