//
//  NewsDetailsViewController.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 06.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailsDisplayLogic: class {
    func displayDetails(viewModel: NewsDetails.ShowDetails.ViewModel)
}

final class NewsDetailsViewController: UIViewController {
    
    
    let detailView = DetailNewsView()
    
    var interactor: NewsDetailsBusinessLogic?
    var router: (NSObjectProtocol & NewsDetailsRoutingLogic & NewsDetailsDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(detailView)
        showDetails()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        detailView.frame = view.bounds
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Do something
    
    func showDetails() {
        let request = NewsDetails.ShowDetails.Request()
        interactor?.showDetails(request: request)
    }
}

extension NewsDetailsViewController: NewsDetailsDisplayLogic {
    
    func displayDetails(viewModel: NewsDetails.ShowDetails.ViewModel) {
        detailView.courseNameLabel.text = viewModel.displayedDetails.courseName
        detailView.numberOfLessonsLabel.text = viewModel.displayedDetails.numberOfLessons
        detailView.numberOfTestsLabel.text = viewModel.displayedDetails.numberOfTests

        guard let image = viewModel.displayedDetails.imageData else { return }
        detailView.courseImage.image = UIImage(data: image)
    }
}
