//
//  NewsDetailsModels.swift
//  News(Clean Swift)
//
//  Created by Kirill Boev on 06.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsDetails {
    // MARK: Use cases
    
    enum ShowDetails {
        struct Request {
        }
        
        struct Response {
            let news: News
        }
        
        struct ViewModel {
            struct DisplayedDetails {
                let courseName: String?
                let numberOfLessons: String?
                let numberOfTests: String?
                let imageData: Data?
            }
            
            let displayedDetails: DisplayedDetails
        }
    }
}
